name: Go Testing

on:
  push:
    branches: ["main", "*"]
  pull_request:
    branches: ["main", "*"]

jobs:
  build:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.3
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -v ./...

      - name: Test (coverage)
        run: go test -cover ./...
